name: Node.js CI

on:
  push:
    branches: [ "mohamedbahaa2001-patch-1" ]
  pull_request:
    branches: [ "mohamedbahaa2001-patch-1" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and Build Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build --if-present

      - name: Install and Build Backend
        working-directory: ./backend
        run: |
          npm ci
          npm run build --if-present

      - name: Test
        run: npm test
